### ISSUE TITLE
浏览器和手机端可以使用吗?

### ISSUE THREAD

**Issue by Danielypzhang** [terwer/siyuan-plugin-importer#28]
在手机和浏览器上好像不可用.

**Comment by terwer** [comment]
没做限制，调用的后端API做的，理论上应该可以。我测试下。

**Comment by terwer** [comment]
经测试，浏览器是可以正常使用的，若您遇到无法使用问题，请升级思源笔记到288dev2以上。请看

https://ld246.com/article/1684327649794/comment/1684501231951?r=terwergreen#comments

有其他问题，换题再次提出。

**Comment by Danielypzhang** [comment]
@terwer 谢谢回复，升级到了2.88 使用浏览器edge，显示文件转换中请稍后，然后就没有任何反应了。 手机是can't open file chooser

**Comment by terwer** [comment]
我晚点验证下，看看问题是否存在。
手机的话我呼呼在2.8.9发布之后适配，原因是思源本体288有一些急需解决的bug。

**Comment by Danielypzhang** [comment]
这个应该是手机端不支持pandoc 导致的,没有安装桌面端,用手机伺服打开浏览器,所以不可以.

**Comment by terwer** [comment]
哦，那就是了。手机端为了体积大小，应该不可能内置pandoc上去。这样的话，就暂时只能通过pc端导入了。
