### ISSUE TITLE
【需求】导入格式支持 .mobi

### ISSUE THREAD

**Issue by git-zxx** [terwer/siyuan-plugin-importer#31]
感谢大佬贡献这么强大的插件！希望可以支持导入mobi格式的文件哇🙏🙏

**Comment by terwer** [comment]
这个我先预研一下，看看技术上实现的可能。

**Comment by terwer** [comment]
研究了一下，可先用 https://products.aspose.app/words/conversion/mobi-to-md 转换，然后用笔记本自带的导入文件夹实现。
