### ISSUE TITLE
能指定子级目录批量导入就非常NICE

### ISSUE THREAD

**Issue by scckele** [terwer/siyuan-plugin-importer#33]
能指定子级目录批量导入就非常NICE
哈哈😄

**Comment by terwer** [comment]
意思是文件下面包含所有带带如文档是吗，类似这样？
![image](https://github.com/terwer/siyuan-plugin-importer/assets/3259282/697c5377-3bf6-4c20-b461-c4758f28fcc9)

**Comment by terwer** [comment]
关联 https://github.com/siyuan-note/siyuan/issues/8325

**Comment by terwer** [comment]
已支持，不过有以下限制

![Uploading ccb09bf37f994d14361058424afac4c1.png…]()
