### ISSUE TITLE
请问，导入文件转为Markdown临时文件后，会自动将Markdown临时文件删除吗

### ISSUE THREAD

**Issue by nuistZPZ** [terwer/siyuan-plugin-importer#49]
请问，导入文件转为Markdown临时文件后，会自动将Markdown临时文件删除吗？如果不会，请问Markdown临时文件在哪

**Comment by terwer** [comment]
有临时文件，临时文件目前是自动删除的。
请问您是否有保留临时文件额需求呢，有的话下版本可提供选择配置。

**Comment by nuistZPZ** [comment]
保留临时文件倒是没想过，因为思源本身可以导出为Markdown。
我是为了导入电子书，如果要保留Markdown格式的电子书，那准是要用正则修改一下里面没删去的东西了。
您说的这个功能算是如虎添翼，让这个插件成为一个优秀的格式转化器，但我觉得增加导入格式可能是更加重要的。https://ld246.com/article/1679134353655
这篇文章的作者，如果当时导入的时候用上大佬您的插件，估计也就没有开头那些话了。hh

**Comment by terwer** [comment]
目前我做了一些处理，就是用正则的。
不知道加上自定义正则替换是否能解决你的需求？

**Comment by nuistZPZ** [comment]
那太好了，我可以直接卸载calibre了
