### ISSUE TITLE
Docker中导入失败

### ISSUE THREAD

**Issue by ZhangHuan95** [terwer/siyuan-plugin-importer#51]
在群晖Docker部署的SiYuan中使用插件导入EPUB。
选择一个文件导入，只会提示导入
<img width="448" alt="image" src="https://github.com/terwer/siyuan-plugin-importer/assets/26647010/14974ca4-6271-4176-a0ca-164ac91a4c02">
之后就没有反应了，并没有创建文档。

**Comment by terwer** [comment]
感谢反馈，我先研究下docker环境能否实现支持。

**Comment by terwer** [comment]
抱歉，受限于 pandoc ，暂不支持 docker。请使用 pc 客户端。
