### ISSUE TITLE
伺服使用时导入失败，怀疑和window.require()有关

### ISSUE THREAD

**Issue by HowcanoeWang** [terwer/siyuan-plugin-importer#82]
有如下的报错：

![image](https://github.com/terwer/siyuan-plugin-importer/assets/19968935/14454971-cdf6-4b3b-b805-5d032a1a3ac1)

之前开发插件的时候，由于electron的安全机制，导致window.require()无法在伺服模式下成功加载，不知道是不是这个原因导致的

[[Electron.js] window.require is not a function 的原因及解決方法](https://weirenxue.github.io/2021/08/05/electron_window_require/)

以及看各个项目源码时，找到的一个可能解决方案？https://github.com/zuoez02/siyuan-plugin-open-md/blob/6713813254a1b6caea80d9cfffda35cf2ad54955/index.js#L16-L34

最简单的就是把伺服端支持给砍掉，毕竟思源笔记本身也不支持伺服的时候导入文件，看了下config的配置没有支持伺服端，但是不知道为啥这个插件在伺服端还是出现了

**Comment by terwer** [comment]
应该和 https://github.com/terwer/siyuan-plugin-importer/pull/89 有关，等升级再试试，不行的话可再提issue
